#!/bin/bash

if [ "$1" = "" ]
then
    echo dbgcpp: error: no arguments provided
    echo usage: dbgcpp file.cpp [argv]
    exit 1
fi

if ! [[ "$1" == *".cpp" ]]
then
    echo dbgcpp: error: file should have '.cpp' extension
    exit 2
fi

base=$(basename -s .cpp $1)

g++ -Wall -lm -g -ggdb -D DEBUG="(1)" -o ./$base $1

if ! [ "$?" -eq "0" ]
then
    exit "$?"
fi

mkdir -p ~/.tmp/dbgcpp/
mv ./$base ~/.tmp/dbgcpp/$base
chmod +x ~/.tmp/dbgcpp/$base

echo debug: $1
gdb -q ~/.tmp/dbgcpp/$base

rm ~/.tmp/dbgcpp/$base
