#!/bin/bash

if [ "$1" = "" ]
then
    echo dbgcpp: error: no arguments provided
    echo usage: dbgcpp file.cpp [argv]
    exit 1
fi

base=$(basename -s .c $1)

echo debug: $1

g++ -Wall -lm -g -ggdb -D DEBUG="(1)" -o ./$base $1

if ! [ "$?" = "0" ]
then
    exit "$?"
fi

mkdir -p ~/.tmp/dbgcpp/
mv ./$base ~/.tmp/dbgcpp/$base
chmod +x ~/.tmp/dbgcpp/$base

gdb ~/.tmp/dbgcpp/$base

rm ~/.tmp/dbgcpp/$base
