#!/bin/bash

if [ "$1" = "" ]
then
    echo runcpp: error: no arguments provided
    echo usage: runcpp file.cpp [argv]
    exit 1
fi

base=$(basename -s .c $1)

echo run: $1

g++ -Wall -lm -o ./$base $1

if ! [ "$?" = "0" ]
then
    exit "$?"
fi

mkdir -p ~/.tmp/runcpp/
mv ./$base ~/.tmp/runcpp/$base
chmod +x ~/.tmp/runcpp/$base

~/.tmp/runcpp/$base "${@:2}"
retval=$?

rm ~/.tmp/runcpp/$base
exit $retval
